#!/bin/sh
#[ "$ACTION" = "add" -o "$ACTION" = "remove" ] && /sbin/block hotplug
sleep 10
# 0 yes blockdevice handles this - 1 no it is not there
BLKDEV=$(dirname "$DEVPATH")
BASENAME=$(basename "$BLKDEV")
DEVICE=$(basename "$DEVPATH")
SKIP=$(block info | sed 's/\(.*\): .*/\1/' | grep -q "$DEVICE"/-e ; echo $?)
#path="$DEVPATH"
START_SERVICE="/etc/init.d/samba4 start ; /etc/init.d/transmission start"
STOP_SERVICE="/etc/init.d/samba4 stop ; /etc/init.d/transmission stop"

#logger -t hotplug "Devpath $DEVPATH"
#logger -t hotplug "Basename $BASENAME"
#logger -t hotplug "Device $DEVICE"
#logger -t hotplug "Skip $SKIP"

if [ "${BASENAME}" != "block" ] && [ -z "${DEVICE##sd*}" ] && [ "${SKIP}" -eq 1 ] ; then
    ISLABEL=$(blkid "/dev/${DEVICE}" | grep -q LABEL/-e ; echo $?)
    #logger -t hotplug "IsLabel $ISLABEL"  
    if [ "${ISLABEL}" -eq 0 ]; 	then
        mntpnt=$(blkid "/dev/${DEVICE}" | sed 's/.*LABEL="\(.*\)" UUID.*/\1/') 
    else
        mntpnt=${DEVICE}
    fi
	#logger -t hotplug "Mountpoint ${mntpnt}"
        case "$ACTION" in
            add)
                        mkdir -p "/mnt/${mntpnt}"
                        logger -t hotplug "Mkdir mnt/${mntpnt}"
                        # Set APM value for automatic spin down
                        /sbin/hdparm -B 127 "/dev/${DEVICE}"
                        # Try to be gentle on solid state devices
			# vfat & ntfs-3g check
			if [ $(which fdisk) ]; then
				isntfs=$(fdisk -l | grep "${DEVICE}" | grep Microsoft)#NTFS
				isvfat=$(fdisk -l | grep "${DEVICE}" | grep FAT)
				isfuse=$(lsmod | grep fuse)
				isntfs3g=$(which ntfs-3g)
			else
				isntfs=""
				isvfat=""
			fi
			#isntfs="1"
			#isfuse="1"
			#isntfs3g="1"
			#logger -t hotplug "Isntfs $isntfs isfuse $isfuse isntfs3g $isntfs3g"
			# mount with ntfs-3g if possible, else with default mount
			if [ "${isntfs}" ] && [ "${isfuse}" ] && [ "${isntfs3g}" ]; then
				ntfs-3g "/dev/${DEVICE}" "/mnt/${DEVICE}"
				logger -t hotplug "Ntfs-3g /dev/${DEVICE} mnt/${DEVICE}"
				chmod ugo+rwx /mnt
			elif [ "$isvfat" ]; then
				mount -o iocharset=utf8 "/dev/${DEVICE} /mnt/${DEVICE}"
			else
				mount "/dev/${DEVICE} /mnt/${DEVICE}"
			fi
                        #mount -o rw,sync,noatime,discard,nls=utf8 /dev/${DEVICE} /mnt/${mntpnt}
			$START_SERVICE
			logger -t hotplug "start samba4&transmission service"
                ;;
            remove)
                        # Once the device is removed, the /dev entry disappear. We need mountpoint
                        mountpoint=$(mount | grep "/dev/${DEVICE}" | sed 's/.* on \(.*\) type.*/\1/')
                        umount -l "${mountpoint}"
			$STOP_SERVICE
			logger -t hotplug "stop samba4&transmission service" 
			logger -t hotplug "Umount ${mountpoint}"
                ;;
        esac
fi
